server:
  port: 8300
spring:
  application:
    name: com-zxl-member
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
swagger:
  base-package: com.zxl.member.service
  title: SpringCloud2.x构建微服务电商项目-会员服务接口
  description: “基于SpringCloud2.x构建微服务电商项目”。
  version: 1.1
  terms-of-service-url: www.zxl.com
  contact:
    name: ZXL 学习
    email: 1207346575@qq.com